parms = dict(
    in_path     = 'data/sampleB', 
    out_file    = 'data/res.tif',
    width       = 1024,
    height      = 1024,
    number      = 1,
    start       = 0,
    scale       = 1,
    xshift      = 0,
    yshift      = 0,
    ring_thick  = 4,
    ring_start  = 4,
    ring_end    = 30,
    ring_step   = 1,
    ring_method = 2,
    likelihoodmask = 13,
    likelihoodmaskinner = 6,
    contrast_c1 = -0.5,
    contrast_c2 = 6,
    contrast_c3 = 4,
    contrast_c4 = 4,
    candi_threshold = 500,
    maxima_sig  = 1.5,
    blob_alpha  = 0.2 )

config = dict (
    schedfixed = True,
    profiling = True,
    deviceCPU = False )
