BUILD_TIF := contrast hough likelihood
BUILD_TXT := candidate azimu
SAMPLES := SampleA SampleB SampleC

OUTROOT := ./output
DATAROOT := ./input
SCRIPT := ../piv-test.py
CONFIG_TMP := tmp.cfg
OUTPUT_TMP := /dev/null
